comments

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -363,6 +363,9 @@ jobs:
           name: make sure the backend changed
           working_directory: ~/project
           command: |
+            # git diff --exit-code will exit with a 0 if there were no changes
+            # or a non-zero if there were changes, so stop this step gracefully
+            # if there were no changes in the api directory
             git diff master --relative=api --name-only --exit-code > /dev/null
             if [ $? -eq "0" ]; then
               circleci-agent step halt
@@ -402,8 +405,11 @@ jobs:
       - run:
           name: make sure the frontend changed
           command: |
+            # git diff --exit-code will exit with a 0 if there were no changes
+            # or a non-zero if there were changes, so stop this step gracefully
+            # if there were no changes in the web directory
             git diff master --relative=web --name-only --exit-code > /dev/null
-            if [ $? -eq "0" ]; thenqgit
+            if [ $? -eq "0" ]; then
               circleci-agent step halt
             fi
       - run:
